include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false 
    
analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'
  errors:
    invalid_annotation_target: ignore