name: submission_jala
description: "JALA Tech Mobile Software Engineer Take Home Test"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # common package
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  logger: ^2.3.0

  # state management
  flutter_bloc: ^8.1.4
  bloc: ^8.1.3

  # network
  dio: ^5.4.0
  
  # generator
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.6.7
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # routing
  auto_route: ^7.8.4

  # ui & widget
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.4
  shimmer: ^3.0.0
  share_plus: ^9.0.0
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/