// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'creator.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$CreatorImpl _$$CreatorImplFromJson(Map<String, dynamic> json) =>
    _$CreatorImpl(
      id: (json['id'] as num?)?.toInt(),
      roleId: (json['role_id'] as num?)?.toInt(),
      name: json['name'] as String?,
      email: json['email'] as String?,
      avatar: json['avatar'] as String?,
      emailVerified: json['email_verified'] as bool?,
      subscriptionTypeId: (json['subscription_type_id'] as num?)?.toInt(),
      settings: json['settings'] == null
          ? null
          : Settings.fromJson(json['settings'] as Map<String, dynamic>),
      createdAt: json['created_at'] as String?,
      updatedAt: json['updated_at'] as String?,
      regionId: json['region_id'] as String?,
      address: json['address'] as String?,
      lastLoginAt: json['last_login_at'] as String?,
      deactivated: json['deactivated'] as bool?,
      expiredAt: json['expired_at'] as String?,
      phone: json['phone'] as String?,
      phoneVerified: json['phone_verified'] as bool?,
      gender: (json['gender'] as num?)?.toInt(),
      occupation: json['occupation'] as String?,
      idNumber: json['id_number'],
      idScan: json['id_scan'],
      tinNumber: json['tin_number'],
      tinScan: json['tin_scan'],
      birthdate: json['birthdate'],
      company: json['company'],
      companyAddress: json['company_address'],
      position: json['position'],
      monthlyIncome: json['monthly_income'],
      incomeSource: json['income_source'],
      buyer: json['buyer'],
      phoneCountry: json['phone_country'] as String?,
      country: json['country'],
      interest: json['interest'] as String?,
      unsubscribeEmailAt: json['unsubscribe_email_at'],
      freshchatRestoreId: json['freshchat_restore_id'],
      allowCreateClient: json['allow_create_client'],
      allowCreateToken: json['allow_create_token'],
      interests: json['interests'],
      familyCardNumber: json['family_card_number'],
      familyCardScan: json['family_card_scan'],
      telegramId: json['telegram_id'],
      genderName: json['gender_name'],
      expiredDate: json['expired_date'],
      expiredTime: json['expired_time'],
      upcomingBirthdate: json['upcoming_birthdate'],
    );

Map<String, dynamic> _$$CreatorImplToJson(_$CreatorImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'role_id': instance.roleId,
      'name': instance.name,
      'email': instance.email,
      'avatar': instance.avatar,
      'email_verified': instance.emailVerified,
      'subscription_type_id': instance.subscriptionTypeId,
      'settings': instance.settings,
      'created_at': instance.createdAt,
      'updated_at': instance.updatedAt,
      'region_id': instance.regionId,
      'address': instance.address,
      'last_login_at': instance.lastLoginAt,
      'deactivated': instance.deactivated,
      'expired_at': instance.expiredAt,
      'phone': instance.phone,
      'phone_verified': instance.phoneVerified,
      'gender': instance.gender,
      'occupation': instance.occupation,
      'id_number': instance.idNumber,
      'id_scan': instance.idScan,
      'tin_number': instance.tinNumber,
      'tin_scan': instance.tinScan,
      'birthdate': instance.birthdate,
      'company': instance.company,
      'company_address': instance.companyAddress,
      'position': instance.position,
      'monthly_income': instance.monthlyIncome,
      'income_source': instance.incomeSource,
      'buyer': instance.buyer,
      'phone_country': instance.phoneCountry,
      'country': instance.country,
      'interest': instance.interest,
      'unsubscribe_email_at': instance.unsubscribeEmailAt,
      'freshchat_restore_id': instance.freshchatRestoreId,
      'allow_create_client': instance.allowCreateClient,
      'allow_create_token': instance.allowCreateToken,
      'interests': instance.interests,
      'family_card_number': instance.familyCardNumber,
      'family_card_scan': instance.familyCardScan,
      'telegram_id': instance.telegramId,
      'gender_name': instance.genderName,
      'expired_date': instance.expiredDate,
      'expired_time': instance.expiredTime,
      'upcoming_birthdate': instance.upcomingBirthdate,
    };
